services:
  home:
    build:
      context: .
      dockerfile: home/Dockerfile
    ports:
      - "3000:3000"
    container_name: home_app

  cart:
    build:
      context: .
      dockerfile: cart/Dockerfile
    ports:
      - "3001:3001"
    container_name: cart_app
